"""R20.2: path classes (D56).

The corpus's false alarms were mostly secrets in tests and docs (R20.1), and a rule
cannot tell a test from the code it tests. The File Set gives every path one class,
`source`, `test`, `fixture`, `docs`, `example`, `vendored` or `generated`, by whole
segments, and each finding carries its path's class as `context`. Identity does not
change: a fingerprint is the same whatever class its path has.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from valvur import pathclass
from valvur.engine_host import LocalRuntime

FAKE_TOOLS = Path(__file__).parent / "fixtures" / "fake-tools"
KEY = "AKIAV7Q2XR4TVBN6WLKJ"


@pytest.mark.parametrize(("path", "expected"), [
    # Whole segments: the OWASP Benchmark lives in `testcode/`, and a substring rule
    # would make track 1 a test suite.
    ("testcode/BenchmarkTest00001.py", "source"),
    ("latest/x.py", "source"),
    ("contest/y.py", "source"),
    ("src/app.py", "source"),
    ("tests/test_app.py", "test"),
    ("test/upgrade.test.js", "test"),
    ("src/__tests__/a.js", "test"),
    ("spec/models/user_spec.rb", "test"),
    ("pkg/thing_test.go", "test"),
    ("test_app.py", "test"),
    ("tests/certs/valid/server/server.key", "test"),
    ("tests/fixtures/app/config.py", "fixture"),
    ("internal/testdata/x.json", "fixture"),
    ("docs/config.rst", "docs"),
    ("examples/basic/main.py", "example"),
    ("vendor/github.com/x/y.go", "vendored"),
    ("third_party/lib/a.c", "vendored"),
    ("web/node_modules/left-pad/index.js", "vendored"),
])
def test_a_path_has_one_class_by_whole_segments(path, expected):
    assert pathclass.of(path) == expected


def test_a_generated_path_is_read_from_gitattributes_and_from_its_header(tmp_path):
    from valvur import fileset

    (tmp_path / ".gitattributes").write_text("api/*.pb.go linguist-generated=true\n"
                                             "dist/** linguist-generated\n")
    (tmp_path / "api").mkdir()
    (tmp_path / "api" / "a.pb.go").write_text("package api\n")
    (tmp_path / "dist").mkdir()
    (tmp_path / "dist" / "bundle.js").write_text("x\n")
    (tmp_path / "models.py").write_text("# Code generated by sqlc. DO NOT EDIT.\nx = 1\n")
    (tmp_path / "app.py").write_text("x = 1  # we do not edit this by hand\n")

    classes = fileset.classes(tmp_path, ["api/a.pb.go", "dist/bundle.js", "models.py",
                                         "app.py", "tests/t.py"])

    assert classes == {"api/a.pb.go": "generated", "dist/bundle.js": "generated",
                       "models.py": "generated", "app.py": "source", "tests/t.py": "test"}


@pytest.fixture
def scanned(tmp_path, monkeypatch) -> Path:
    from valvur import api, cache
    from valvur.adapters import GitleaksAdapter

    monkeypatch.delenv("VALVUR_ENGINE", raising=False)
    monkeypatch.setattr(cache, "root", lambda: tmp_path / "cache")
    ws = tmp_path / "ws"
    (ws / "tests").mkdir(parents=True)
    (ws / "config.py").write_text(f"KEY = '{KEY}'\n")
    (ws / "tests" / "test_config.py").write_text(f"KEY = '{KEY}'\n")
    api.scan(ws, runner=LocalRuntime(FAKE_TOOLS), adapters=[GitleaksAdapter()])
    return ws


def test_every_finding_carries_its_context_in_findings_json_and_sarif(scanned):
    results = scanned / ".security-scan"
    findings = json.loads((results / "findings.json").read_text())["findings"]
    by_path = {f["path"]: f["context"] for f in findings}
    assert by_path == {"config.py": "source", "tests/test_config.py": "test"}

    sarif = json.loads((results / "results.sarif").read_text())
    contexts = {r["locations"][0]["physicalLocation"]["artifactLocation"]["uri"]:
                r["properties"]["context"] for r in sarif["runs"][0]["results"]}
    assert contexts == by_path


def test_a_findings_identity_does_not_depend_on_its_class(scanned, monkeypatch):
    from valvur import api
    from valvur.adapters import GitleaksAdapter

    def fingerprints() -> dict[str, str]:
        doc = json.loads((scanned / ".security-scan" / "findings.json").read_text())
        return {f["path"]: f["fingerprint"] for f in doc["findings"]}

    before = fingerprints()
    monkeypatch.setattr(pathclass, "of", lambda path: "vendored")
    api.scan(scanned, runner=LocalRuntime(FAKE_TOOLS), adapters=[GitleaksAdapter()])

    assert fingerprints() == before
