"""R21.1: the README's demo is the CLI's own output, small, and holds nothing private.

`scripts/demo.py` scans acceptance repository 8 through the CLI and renders what it
printed as `docs/demo.svg` (D48a). These tests read the committed file: under 1 MB,
the verdict and the malicious package in it, no path of the machine that made it and
nothing a secret scanner would flag. The end-to-end test runs the script again and
finds the same lines, so the file cannot drift from the CLI unseen.
"""

from __future__ import annotations

import ast
import importlib.util
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
SVG = REPO / "docs" / "demo.svg"
#: The README's first screen, in lines: what a reader sees before scrolling.
FIRST_SCREEN = 24


def _demo():
    spec = importlib.util.spec_from_file_location("demo", REPO / "scripts" / "demo.py")
    module = importlib.util.module_from_spec(spec)  # type: ignore[arg-type]
    spec.loader.exec_module(module)  # type: ignore[union-attr]
    return module


def _text(svg: str) -> list[str]:
    root = ET.fromstring(svg)  # noqa: S314 — the file this repository renders
    return [t.text or "" for t in root.iter("{http://www.w3.org/2000/svg}text")]


def test_the_script_uses_the_standard_library_alone():
    for path in (REPO / "scripts" / "demo.py", REPO / "scripts" / "acceptance" / "generate.py"):
        tree = ast.parse(path.read_text())
        names = {alias.name.split(".")[0] for node in ast.walk(tree)
                 if isinstance(node, ast.Import) for alias in node.names}
        names |= {node.module.split(".")[0] for node in ast.walk(tree)
                  if isinstance(node, ast.ImportFrom) and node.module and not node.level}
        assert names - {"generate", "__future__"} <= sys.stdlib_module_names, (path, names)


def test_a_capture_renders_every_line_in_order_and_neutralises_the_path(tmp_path):
    demo = _demo()
    workspace = tmp_path / "somewhere" / "acceptance-8"
    printed = f"findings: 1 active\nresults: {workspace}/.security-scan\n"

    svg = demo.render([("valvur scan .", demo.neutral(printed, workspace))])

    assert _text(svg) == ["~/acceptance-8 $ valvur scan .", "findings: 1 active",
                          "results: ~/acceptance-8/.security-scan"]
    assert str(tmp_path) not in svg


def test_the_committed_demo_is_small_and_shows_the_verdict_and_the_package():
    svg = SVG.read_text(encoding="utf-8")
    text = "\n".join(_text(svg))

    assert len(svg.encode()) < 1024 * 1024
    assert re.search(r"^findings: \d+ active$", text, re.M)
    assert "@hyperion-util/cookies was published as malicious" in text
    assert "Generated by scripts/demo.py" in svg


def test_the_committed_demo_holds_no_path_of_this_machine_and_no_secret():
    svg = SVG.read_text(encoding="utf-8")

    for private in ("/Users/", "/home/", "/root", "/tmp/", "/private/", "/var/folders",  # noqa: S108
                    "C:\\"):
        assert private not in svg, private
    for secret in (r"AKIA[0-9A-Z]{16}", r"gh[pousr]_[A-Za-z0-9]{36}", r"sk-[A-Za-z0-9]{20}",
                   r"xox[abp]-", "PRIVATE" + " KEY"):
        assert not re.search(secret, svg), secret


def test_the_readme_shows_it_on_its_first_screen():
    first = (REPO / "README.md").read_text().splitlines()[:FIRST_SCREEN]

    assert any("docs/demo.svg" in line for line in first)


@pytest.mark.e2e
def test_running_the_script_again_prints_the_same_lines(tmp_path):
    demo = _demo()

    assert demo.main(["--out", str(tmp_path / "demo.svg")]) == 0

    assert _text((tmp_path / "demo.svg").read_text()) == _text(SVG.read_text())
