#!/usr/bin/env python3
"""`fake-cat-cwd NAME REPORT`: copy NAME from the working directory to REPORT (R3.9)."""
import sys

with open(sys.argv[1], encoding="utf-8") as src, open(sys.argv[2], "w", encoding="utf-8") as out:
    out.write(src.read())
