#!/usr/bin/env python3
"""`fake-sleep SECONDS REPORT`: sleep, then write `[]` to REPORT (R3.4)."""
import sys
import time

time.sleep(float(sys.argv[1]))
with open(sys.argv[2], "w", encoding="utf-8") as handle:
    handle.write("[]")
