"""Record the README's demo: one CLI scan of acceptance repository 8 (R21.1, D48a).

Writes `docs/demo.svg`, an animated terminal, from what the CLI prints when it scans
the repository whose lockfile pins a package published as malicious, and then lists
the findings. The SVG is rendered here from the captured text with the standard
library alone, so no recorder is installed and the file never drifts from the CLI:
running this again regenerates it. The workspace's path on this machine is written
as `~/acceptance-8`, so the file holds no path of the machine that made it.

    uv run python scripts/demo.py [--out docs/demo.svg]
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from xml.sax.saxutils import escape

REPO = Path(__file__).resolve().parent.parent
#: How the workspace is named in the recording, wherever it was scanned.
SHOWN = "~/acceptance-8"
#: What the recording runs, in order, inside the workspace.
COMMANDS = (("scan", "."), ("findings",))

FONT_PX, LINE_PX, CHAR_PX, PAD_PX = 14, 20, 8.4, 16
#: Seconds per typed character, then the pause before a command's output appears.
TYPE_S, RUN_S, LINE_S = 0.05, 0.8, 0.15


def capture(workspace: Path) -> list[tuple[str, str]]:
    """Each command as typed, and what the CLI printed for it, with the workspace's
    real path replaced by `SHOWN`."""
    steps = []
    for args in COMMANDS:
        done = subprocess.run(  # noqa: S603 — this interpreter, the CLI
            [sys.executable, "-c", "from valvur.cli import main; raise SystemExit(main())",
             *args], cwd=workspace, capture_output=True, text=True, check=False)
        steps.append(("valvur " + " ".join(args), neutral(done.stdout + done.stderr,
                                                          workspace)))
    return steps


def neutral(text: str, workspace: Path) -> str:
    """The text with this machine's paths written as the reader's would be."""
    for real in sorted({str(workspace), str(workspace.resolve())}, key=len, reverse=True):
        text = text.replace(real, SHOWN)
    return text.replace(str(Path.home()), "~").rstrip() + "\n"


def lines(steps: list[tuple[str, str]]) -> list[tuple[str, str, float]]:
    """(kind, text, the second it appears) for every line of the recording."""
    out, at = [], 0.5
    for n, (command, output) in enumerate(steps):
        if n:
            out.append(("output", "", at))
        out.append(("prompt", f"{SHOWN} $ {command}", at))
        at += TYPE_S * len(command) + RUN_S
        for line in output.splitlines():
            out.append(("output", line, at))
            at += LINE_S
        at += 1.0
    return out


def render(steps: list[tuple[str, str]]) -> str:
    """An SVG terminal whose lines appear in turn and then stay, so a reader that
    does not animate sees the whole run."""
    shown = lines(steps)
    width = int(2 * PAD_PX + CHAR_PX * max(len(text) for _, text, _ in shown))
    height = int(2 * PAD_PX + 28 + LINE_PX * len(shown))
    rows = []
    for n, (kind, text, at) in enumerate(shown):
        y = PAD_PX + 28 + LINE_PX * (n + 1) - 6
        rows.append(f'<text class="{kind}" x="{PAD_PX}" y="{y}" '
                    f'style="animation-delay:{at:.2f}s">{escape(text)}</text>')
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" \
viewBox="0 0 {width} {height}" role="img" aria-label="valvur scanning a project whose \
lockfile pins a malicious package">
<!-- Generated by scripts/demo.py from the CLI's own output; do not edit by hand. -->
<style>
text {{ font: {FONT_PX}px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  white-space: pre; opacity: 0; animation: show 0.01s linear both; }}
.prompt {{ fill: #8be9fd; }} .output {{ fill: #f8f8f2; }}
@keyframes show {{ to {{ opacity: 1; }} }}
</style>
<rect width="{width}" height="{height}" rx="8" fill="#1e1f29"/>
<circle cx="20" cy="18" r="5" fill="#ff5f56"/><circle cx="38" cy="18" r="5" \
fill="#ffbd2e"/><circle cx="56" cy="18" r="5" fill="#27c93f"/>
{chr(10).join(rows)}
</svg>
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=REPO / "docs" / "demo.svg")
    args = parser.parse_args(argv)
    sys.path.insert(0, str(REPO / "scripts" / "acceptance"))
    import generate  # type: ignore[import-not-found]

    with tempfile.TemporaryDirectory() as scratch:
        [source] = generate.build(Path(scratch) / "set", "8").values()
        workspace = Path(scratch) / "acceptance-8"
        shutil.copytree(source, workspace)
        shutil.rmtree(workspace / ".security-scan", ignore_errors=True)
        svg = render(capture(workspace))
    args.out.write_text(svg, encoding="utf-8")
    print(f"wrote {args.out.relative_to(REPO) if args.out.is_relative_to(REPO) else args.out}"
          f", {len(svg.encode()) / 1024:.1f} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
