"""`docs/RULES.md`: every shipped rule's precision, measured (R29.3, D65b).

    uv run python scripts/rules_doc.py            # write docs/RULES.md
    uv run python scripts/rules_doc.py --check    # exit 1 when it is not current

Rendered from `tests/eval/rules-measured.json`, which `scripts/eval.py --rules-measured`
writes from the Score's scans of tracks 1 and 2 and the corpus. The bar and each
rule's state are `scripts/eval/rule_precision.py`'s, so the page and the test that
keeps active rules over the bar read one definition.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts" / "eval"))

import rule_precision  # type: ignore[import-not-found]  # noqa: E402

MEASURED = REPO / "tests" / "eval" / "rules-measured.json"
PAGE = REPO / "docs" / "RULES.md"


def _cell(counts: dict) -> str:
    cell = f"{counts['tp']} / {counts['fp']}"
    return f"{cell}, {counts['unjudged']} unjudged" if counts.get("unjudged") else cell


def render(measured: dict) -> str:
    lines = [
        "<!-- Generated by scripts/rules_doc.py from tests/eval/rules-measured.json; do not",
        "     edit by hand. -->",
        "",
        "# The rules valvur ships, and how precise each is",
        "",
        "Every static-analysis rule valvur runs through Opengrep, measured on what valvur",
        "reports over the Score's track 1 (the OWASP Benchmark for Python), track 2 (the",
        f"JavaScript twins) and the corpus of {measured['corpus_projects']} real projects, "
        "whose every",
        "active finding is labelled by hand (`tests/eval/labels/corpus.toml`). A cell is",
        "true / false positives; a finding on a case of another weakness is not counted.",
        "",
        "**The bar** is D29's: at least one true positive and a precision of at least 0.5",
        "over the three, and for a rule vendored from GitLab's `sast-rules`, one true",
        "positive at a line valvur's own rules do not already report. A rule under it is",
        "moved to the **inventory**, where its findings are reported for review and never",
        "count toward the verdict, with the reason below. The sink rules are inventory by",
        "design (D47a); an inventory finding on the corpus has no label, and is *unjudged*.",
        "",
        "**Unmeasured** means no case of the rule's weakness in any of the three, so",
        "nothing here says how precise it is. Each fires on the cases planted for it in",
        "valvur's own tests and fixtures, and stays active.",
        "",
        "| rule | source | CWE | track 1 | track 2 | corpus | precision | state |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for rule, row in sorted(measured["rules"].items()):
        places = row["places"]
        source = "GitLab sast-rules" if row["vendored"] else "valvur"
        cwe = ", ".join(f"CWE-{n}" for n in row["cwe"]) or "-"
        measured_at_all = row["tp"] + row["fp"]
        lines.append(
            f"| `{rule}` | {source} | {cwe} | {_cell(places['sast-python'])} | "
            f"{_cell(places['sast-js'])} | {_cell(places['corpus'])} | "
            f"{row['precision'] if measured_at_all else '-'} | {rule_precision.state(row)} |")
    lines += ["", f"Measured {measured['measured']} on `valvur:dev` (`{measured['image']}`).",
              ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 when not current")
    args = parser.parse_args(argv)
    page = render(json.loads(MEASURED.read_text(encoding="utf-8")))
    if args.check:
        if not PAGE.is_file() or PAGE.read_text(encoding="utf-8") != page:
            print("docs/RULES.md is not current; run scripts/rules_doc.py", file=sys.stderr)
            return 1
        return 0
    PAGE.write_text(page, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
